Mingw doesn't support %lld format, so lets use an alternative.
This avoids GCC warning:
  result.c: In function 'rb_tinytds_result_fetch_row':
  result.c:241:11: warning: unknown conversion type character 'l' in format [-Wformat]
  result.c:241:11: warning: too many arguments for format [-Wformat-extra-args]